### ISSUE TITLE
GitReader.Repository.Factory.OpenStructureAsync throws "Offset and length were out of bounds"

### ISSUE THREAD

**Issue by holmbergjonas** [kekyo/GitReader#14]
When opening the repository https://github.com/ethereum/solc-bin using GitReader.Repository.Factory.OpenStructureAsync I get the following exception:

```
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at GitReader.Internal.Utilities.MakeBigEndian(Byte[] buffer, Int32 index, Int32 size) in /_/GitReader.Core/Internal/Utilities.cs:line 225
   at GitReader.Internal.IndexReader.ReadIndexAsync(String indexPath, IFileSystem fileSystem, BufferPool pool, CancellationToken ct) in /_/GitReader.Core/Internal/IndexReader.cs:line 163
   at GitReader.Internal.ObjectAccessor.GetOrCacheIndexEntryAsync(String indexFileRelativePath, CancellationToken ct) in /_/GitReader.Core/Internal/ObjectAccessor.cs:line 227
   at GitReader.Internal.Utilities.WhenAll[T](ValueTask`1[] tasks)
   at GitReader.Internal.ObjectAccessor.OpenFromPackedAsync(Hash hash, Boolean disableCaching, CancellationToken ct) in /_/GitReader.Core/Internal/ObjectAccessor.cs:line 624
   at GitReader.Internal.ObjectAccessor.OpenAsync(Hash hash, Boolean disableCaching, CancellationToken ct) in /_/GitReader.Core/Internal/ObjectAccessor.cs:line 679
   at GitReader.Internal.RepositoryAccessor.ParseObjectBodyAsync(Repository repository, Hash hash, Func`2 validateType, Action`2 gotLine, CancellationToken ct) in /_/GitReader.Core/Internal/RepositoryAccessor.cs:line 690
   at GitReader.Internal.RepositoryAccessor.ReadTagAsync(Repository repository, Hash hash, CancellationToken ct) in /_/GitReader.Core/Internal/RepositoryAccessor.cs:line 815
   at GitReader.Structures.StructuredRepositoryFacade.<>c__DisplayClass4_0.<<GetStructuredTagsAsync>b__4>d.MoveNext() in /_/GitReader.Core/Structures/StructuredRepositoryFacade.cs:line 118
--- End of stack trace from previous location ---
   at GitReader.Structures.StructuredRepositoryFacade.GetStructuredTagsAsync(StructuredRepository repository, WeakReference rwr, CancellationToken ct) in /_/GitReader.Core/Structures/StructuredRepositoryFacade.cs:line 103
   at GitReader.Internal.Utilities.Join[T0,T1,T2,T3](Task`1 task0, Task`1 task1, Task`1 task2, Task`1 task3)
   at GitReader.Structures.StructuredRepositoryFacade.InternalOpenStructuredAsync(String repositoryPath, IFileSystem fileSystem, CancellationToken ct) in /_/GitReader.Core/Structures/StructuredRepositoryFacade.cs:line 191
   at GitReader.Structures.StructuredRepositoryFacade.OpenStructuredAsync(String path, IFileSystem fileSystem, CancellationToken ct) in /_/GitReader.Core/Structures/StructuredRepositoryFacade.cs:line 218
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__CollectData|0>d.MoveNext() in
```

**Comment by kekyo** [comment]
@holmbergjonas Sorry later, I reproduced it and found a bug in a reading large offset table and fixed.
Will be released next version 1.9.0 soon.

If you're still interested in GitReader, please give it a try.

**Comment by kekyo** [comment]
I will close for a while. If you have any problems, please reopen the page.
